### ISSUE TITLE
Native Share This button takes up too much vertical space

### ISSUE THREAD

**Issue by mattb** [spacehackers/luti#100]
On desktop-class screens on browsers that support the native Share API (e.g. Mac Desktop Safari at least on Catalina, iPadOS 13) the Share This button takes up too much vertical space. 

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/3785/70208562-c0b92300-16e2-11ea-86d3-506a65d549b2.png">

Can anyone who knows CSS better than I do help fix?

**Comment by ariel** [comment]
Design direction - make button just have equal-width gray area surrounding the text, and should be anchored more to the right, similar to the share buttons on Chrome.
