### ISSUE TITLE
Starter GIF implementation

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#11]
Implement tardigrade Starter GIF for mobile and desktop. Starter GIF already created and uploaded.

**Comment by mattb** [comment]
e.g. 
![out](https://user-images.githubusercontent.com/3785/67652468-52728b00-f902-11e9-9390-48aba33ddc19.gif)

**Comment by mattb** [comment]
Believe this is no longer necessary as we have an intro message (and timeout message), and lower-resolution HLS streams for slower connections.
