### ISSUE TITLE
What's This and Share buttons are cropped off the bottom of the screen in landscape mode on iPhone

### ISSUE THREAD

**Issue by mattb** [spacehackers/luti#116]
tested on iPhone 11 Pro

![IMG_0407](https://user-images.githubusercontent.com/3785/72030481-ee434000-323d-11ea-8388-87cd86624f83.png)

![IMG_0408](https://user-images.githubusercontent.com/3785/72030484-f0a59a00-323d-11ea-83c0-69673c686255.png)

**Comment by basilleaf** [comment]
Seems fixed now
