### ISSUE TITLE
Social Media Preview

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#16]
Create a design and write copy to show up in cards for Twitter and Facebook. Implement the design into the code.

**Comment by mattb** [comment]
Separate from "Share this deep link"

**Comment by ariel** [comment]
Twitter card code:

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:creator" content="@arielwaldman">
<meta name="twitter:title" content="Life Under the Ice">
<meta name="twitter:description" content="An exploratory tour through the microscopic world of Antarctica. Each microbe tells a story of the weird and whimsical life in Antarctica that is otherwise invisible to the naked eye.">
<meta name="twitter:image" content="https://lifeundertheice.org/TwitterCard_Tardigrade.png">

Twitter card validator:
https://cards-dev.twitter.com/validator

Facebook Open Graph code:
<meta property="og:url"                content="https://lifeundertheice.org" />
<meta property="og:type"               content="website" />
<meta property="og:title"              content="Life Under the Ice" />
<meta property="og:description"        content="An exploratory tour through the microscopic world of Antarctica. Each microbe tells a story of the weird and whimsical life in Antarctica that is otherwise invisible to the naked eye." />
<meta property="og:image"              content="https://lifeundertheice.org/TwitterCard_Tardigrade.png" />

Facebook validator:
https://developers.facebook.com/tools/debug/sharing/
