### ISSUE TITLE
Search Engine Crawler Preview

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#17]
Write copy for Search Engine preview and crawling. Check that site design is considered crawl-able and has no mobile usability issues according to Google. Enable mobile-first indexing via Google. Ask Google to crawl site.

**Comment by ariel** [comment]
Also need to create and implement a Favicon

**Comment by mattb** [comment]
Also create a sitemap to hit each of the deep links to videos so that the crawler sees the "What's This" content.
