### ISSUE TITLE
Zooming Out on Mobile Causes Website Reload/Error

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#62]
When you are on LUTI on mobile Safari - try zooming-out a significant amount, and the website will either reload or throw an error. When it throws an error it says "A problem repeatedly occurred on [LUTI specific link including geo coordinates]".

**Comment by ariel** [comment]
Weirdly, if you first Zoom In a lot, then when you try to Zoom Out a lot, it doesn't happen. So, only showing up when you go from default view to trying to Zoom Out significantly.

**Comment by mattb** [comment]
I believe that https://github.com/spacehackers/luti/commit/e165bed9502b030e939bf107772789537a632a5e will have fixed this, please re-open if not.

**Comment by mattb** [comment]
Feeling good about the fix in a76ea1d
