### ISSUE TITLE
Dragging (and pinch-zooming on mobile) on the map part of the page has inconsistent behavior

### ISSUE THREAD

**Issue by mattb** [spacehackers/luti#64]
Sometimes drags or zooms the whole web page, not just the map section. Sometimes doesn't register a drag at all.

**Comment by basilleaf** [comment]
this is maybe fixed, I was calling it the "scrollbar issue"

**Comment by basilleaf** [comment]
not sure if this is still happening, some of the hidden things like Intro and Info were still taking space on the page, fixing that fixed a couple other bugs and possibly this one too.

**Comment by mattb** [comment]
looking great now! I'll reopen if I find any new problems :)
