### ISSUE TITLE
Info Box can be dragged into view on Mobile by accident

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#90]
On Mobile, when dragging around, it's possible to drag the Info Box up from the bottom of the screen without selecting the "What's This?" button. Video of interaction attached.
[RPReplay_Final1575094226.MP4.zip](https://github.com/spacehackers/luti/files/3906786/RPReplay_Final1575094226.MP4.zip)

**Comment by mattb** [comment]
Related: #64
