### ISSUE TITLE
CSS height of Info Box needs to adjust to fit all text

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#94]
Info Box height needs to adjust/expand to fit all the text (headline & description) and share button(s) on screen. Example screenshot attached where all elements should be displayed on screen without overlapping or needing to scroll. In this example, the line height (distance between each line) for H1/header text should also be made shorter.
![IMG_2035](https://user-images.githubusercontent.com/48657/69922711-ae758580-1453-11ea-88f6-cf761b791414.PNG)

**Comment by basilleaf** [comment]
hmm I don't see the Share This button locally 🤔

**Comment by ariel** [comment]
@basilleaf Huh. I see it on lifeundertheice.org on my phone. If it's not displaying for you (and it's not due to the CSS), then I'd add it as an issue to @mattb

**Comment by basilleaf** [comment]
oh weirdddd i see it at that url too on my phone, but don't see at that url in simulator, and don't see it anywhere from localhost even on phone.

**Comment by basilleaf** [comment]
will look at this later

**Comment by basilleaf** [comment]
ohhh I see why
