### ISSUE TITLE
Height of Info Box in Desktop should adjust to fit content

### ISSUE THREAD

**Issue by ariel** [spacehackers/luti#97]
On Desktop, the height of the Info Box should adjust to the content (title, description, sharing buttons). Ideally, the same margin/padding on top should be used for the bottom.

Current example of excessive space at the bottom
<img width="1340" alt="Screen Shot 2019-12-01 at 7 45 39 PM" src="https://user-images.githubusercontent.com/48657/69929252-3ae37080-1473-11ea-9660-1f0ef7fb68b3.png">
 attached.

**Comment by basilleaf** [comment]
there is a complication that the `What's this` button is not flowing with the info box as it opens/closes
